import Head from 'next/head'
import Link from 'next/link'
import dynamic from 'next/dynamic'

const getComponents = async () => {
  const data = await fetch('http://localhost:3000/api/blocks');
  const result = await data.json();
  return result.map(({ name, ssr }) => (
    {
      component: dynamic(() => import('../components/SanitizedComponent'),
        { ssr: ssr }),
      name
    }
  ))
}
const components = await getComponents();

const HelloWorld = dynamic(() => import('../components/helloWorld'));
export async function getStaticProps(context) { 
  const data = await fetch('http://localhost:3000/api/cms');
  const result = await data.json();
  return {
    props: { content: result }, // will be passed to the page component as props
  }
}

export default function Home({ content }) {
  const hello = [
    {key: 'key1', name: 'Hello1'},
    {key: 'key2', name: 'Hello2'},
  ]
  return (
    <div className="font-sans flex flex-col h-screen w-full items-center align-middle">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="//unpkg.com/alpinejs" defer></script>
      </Head>

      <main className='m-2 p-2 flex flex-col w-full'>
        <h1 className="text-gray-700 font-bold text-4xl text-center m-2">
          Welcome to <a href="https://nextjs.org" className='hover:underline text-blue-700'>Next.js!</a>
        </h1>
        <h2 className="text-gray-700 font-bold text-baseline text-center m-2">
          <Link href="/demo" className='hover:underline text-blue-700'>Demo</Link>
        </h2>
        <HelloWorld data={hello}/>
        <div className='flex flex-col w-full space-y-2'>
          {components.map((component, index) => {
            const MyCompo = component.component;
            const data = content.find((c) => c.name === component.name);
            const contentHTML = data && data.contentHTML ? data.contentHTML : '<p>No Content</p>';
            return (
              <MyCompo key={index} contentHTML={contentHTML} />)
          })}
        </div>

      </main>


    </div>
  )
}
